# Hereda de la etapa de build del Dockerfile base
FROM node:18 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Hereda de la etapa de producción del Dockerfile base
FROM nginx:alpine AS final
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
