# Etapa de build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa final con Nginx
FROM nginx:alpine AS final
# Copia el build final
COPY --from=builder /app/dist /usr/share/nginx/html
# Copia el archivo de configuración Nginx al mismo nivel del Dockerfile
COPY ./geobizi.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]