version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod # Usa el Dockerfile de producción
    container_name: vue_frontend
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: python_backend
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    # No se exponen puertos directamente en producción, el proxy inverso se encarga

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
