version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    container_name: vue_frontend_dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run serve
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: python_backend_dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    env_file:
      - ./.env
