version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
